openapi: 3.0.3
info:
  title: Adrenaline TruProfit API
  description: |-
    `Introduction`
  
    This is the API for the Adrenaline TruProfit API.
    
    This allows the user to send odds for adjustment to our APIs, which will respond with adjusted odds where appropriate.
    
    Settlement data may also be sent to TruProfit so that users may be analyzed and classified for future adjustment.
    
    `How to Use The API` 
    
    In general, it is expected that you use the login call first with a valid API key, and then use the API Session Token for subsequent calls to any other API Interface.
    
    This API requires an API key, if you don't have one, please [contact us](https://www.adrenalineip.com/#contact).
    
    `Use Of The API`
    
    Use of this API is subject to our terms and conditions, see [Terms](https://www.adrenalineip.com/terms)
    
    Access and use of this API is granted on the understanding that it will be used in accordance with our terms and conditions.  
    
    Sharing of this API with other third parties is strictly prohibited without the express approval of Adrenaline in writing.
    
    NOTE: If you wish to explore other integration options, please [contact us](https://www.adrenalineip.com/#contact)

    _If you have any questions, please contact us via [our website](https://www.adrenalineip.com/#contact)_
    
    `Useful Links`
    
    - [Adrenaline](https://www.adrenalineip.com)
    - [TruProfit](http://truprofit.io/)
  termsOfService: https://adrenalineip.com/terms/
  contact:
    email: luke.campbell@adrenalineip.com
  license:
    name: Proprietary
    url: https://adrenalineip.com/licenses/license-1.0.html
  version: 1.0.3
externalDocs:
  description: Find out more about TruProfit
  url: http://adrenalineip.com
servers:
  - url: https://dev.truprofit.io/api/truprofit/personalization/v1
tags:
  - name: Authentication
    description: Authentication via the adjustment api
    externalDocs:
      description: Find out more
      url: http://adrenalineip.com/products/truprofit/authentication
  - name: Adjustment
    description: Calling the adjustment api
    externalDocs:
      description: Find out more
      url: http://adrenalineip.com/products/truprofit/adjustment
  - name: Settlement
    description: Calling the adjustment api with a settlement
    externalDocs:
      description: Find out more
      url: http://adrenalineip.com/products/truprofit/settlement
paths:
  /login:
    post:
      tags:
        - 'Authentication'
      security: []
      summary: Obtain an API Access Token via login
      operationId: login
      parameters:
        - in: header
          name: x-api-key
          schema:
            type: string
            format: uuid
          example: abcde-abcde-abcde  
          required: true
      responses:
        '200':
          description: The token result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '401':
          description: Invalid credentials
        '422':
          description: 'Malformed request: fields are missing or are supplied in an invalid format'
          content:
            application/json:
              example:
                message: The given data was invalid.
                errors:
                  x-api-key:
                    - "The x-api-key field is required."
  /adjustment:
    post:
      tags:
        - Adjustment
      summary: Send an odds for adjustment to TruProfit
      description: This is for a single set of odds to be supplied to the user.
      operationId: singleOddsAdjust
      parameters:
        - in: header
          name: x-session-token
          schema:
            type: string
            format: uuid
          example: abcde-abcde-abcde  
          required: true
      requestBody:
        description: This is a call that takes a single set of odds and applies an adjustment if appropriate.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdjustmentRequestSimple'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdjustmentSingleOutput'          
        '401':
          description: Invalid token
        '403':
          description: Expired token credentials - please call login again   
      security:
        - adr_auth:
            - write:odds
            - read:odds
  /adjustments:
    post:
      tags:
        - Adjustment
      summary: Batch odds adjustment interface for TruProfit
      description: Multiple odds can be provided.
      operationId: batchOddsAdjust
      parameters:
        - in: header
          name: x-session-token
          schema:
            type: string
            format: uuid
          example: abcde-abcde-abcde  
          required: true
      requestBody:
        description: This is a call that takes a number of different odds for one user and applies adjustments where appropriate.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdjustmentRequestBatch'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdjustmentBatchOutput'
        '401':
          description: Invalid token
        '403':
          description: Expired token credentials - please call login again   
      security:
        - adr_auth:
            - write:odds
            - read:odds
  /settlement:
    post:
      tags:
        - Settlement
      summary: Send a notification of a settlement event to TruProfit
      description: This call allows the outcome of a settlement of a bet to be sent to truprofit so we can see the outcome of it.
      operationId: settlementCall
      parameters:
        - in: header
          name: x-api-key
          schema:
            type: string
            format: uuid
          example: abcde-abcde-abcde  
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettlementRequestSimple'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SettlementRequestSimple'          
        '401':
          description: Invalid token
        '403':
          description: Expired token credentials - please call login again   
      security:
        - adr_auth:
            - write:odds
            - read:odds            
components:
  schemas:
    Token:
      type: object
      properties:
        sessionKey:
          type: string
          description: The session token
          example: eyJhb1cioiJIVCJ9.eyAixjMdNTY31D1wIioNSiW0jxTyT5TyCjIxOTI3MjJ9.kOkTVr4rPq5wiv2W1bB1UQ
    AdjustmentSingleOutput:
      type: object
      properties:
        requestId:
          type: string
          example: abcd-abcd
        prebetId:
          type: string
          example: abcd-abcd
        userId:
          type: string
          example: "abcde-abcde-abcde"
        odds:
          type: array
          items:
            $ref: '#/components/schemas/AdjustedOddPart'
    AdjustmentBatchOutput:
      type: object
      properties:
        requestId:
          type: string
          example: abcd-abcd
        prebetId:
          type: string
          example: abcd-abcd
        userId:
          type: string
          example: "abcde-abcde-abcde"
        eventOddsToAdjust:
          type: array
          items:
            $ref: '#/components/schemas/AdjustmentRequestBatchSimple'          
    AdjustedOddPart:
      type: object
      properties:
        label:
          type: string
          example: 1x2
        odds:
          type: string
          example: 1.87
        probability:
          type: number
          example: 10.23
        newOdd:
          type: string
          example: 1.87
        newProbability:
          type: number
          example: 10.23
    AdjustmentRequestBatch:
      type: object
      properties: 
        userId:
          type: string
          example: "abcde-abcde"
        userLocation:
          type: string
          example: "London, UK"
        prebetId:
          type: string
          example: "abcde-abcde-abcde"
        eventOddsToAdjust:
            type: array
            items:
              $ref: '#/components/schemas/AdjustmentRequestBatchSimple'  
    AdjustmentRequestBatchSimple:
      type: object
      properties:
        startTime:
          type: string
          example: "1671511820"
        sport:
          type: string
          example: "Soccer"
        league:
          type: string
          example: "English Premiership"
        market:
          type: string
          example: "1x2"
        eventPart:
          type: string
          example: "Whole Match"
        betType:
          type: string
          example: "Single"
        currency:
          type: string
          example: "USD" 
        isPrematch:
          type: string
          example: "Pre-match"
        oddsType:
          type: string
          example: "Decimal, US" 
        odds:
            type: array
            items:
              $ref: '#/components/schemas/OddsPair' 
        event:
          type: string
          example: "Man Utd vs. Chelsea"
        selection:
          type: string
          example: "1x2:1"
    AdjustmentRequestSimple:
      type: object
      properties:
        userId:
          type: string
          example: "abcde-abcde-abcde"
        prebetId:
          type: string
          example: "abcde-abcde-abcde"
        startTime:
          type: string
          example: "1671511820"
        sport:
          type: string
          example: "Soccer"
        league:
          type: string
          example: "English Premiership"
        market:
          type: string
          example: "1x2"
        eventPart:
          type: string
          example: "Whole Match"
        betType:
          type: string
          example: "Single"
        currency:
          type: string
          example: "USD" 
        isPrematch:
          type: string
          example: "Pre-match"
        oddsType:
          type: string
          example: "Single" 
        odds:
            type: array
            items:
              $ref: '#/components/schemas/OddsPair' 
        event:
          type: string
          example: "Man Utd vs. Chelsea"
        selection:
          type: string
          example: "1x2:1"
        userLocation:
          type: string
          example: "Chicago, IL"
    OddsPair:
      type: object
      properties:
        oddsLabel:
          type: string
          example: "1" 
        odds:
          type: number
          example: 2.50 
    SettlementRequestSimple:
      type: object
      properties:
        betId:
          type: string
          example: "abcde-abcde"
        prebetId: 
            type: string
            example: "1234-abc-def"
        legId: 
            type: integer
            format: int64
            example: 1
        userId: 
            type: string
            example: "1234-abc-def"  
        betTime: 
            type: string
            example: "1234567898"
        sport:
            type: string
            example: "Soccer"
        league:
            type: string
            example: "Serie A"
        event:
            type: string
            example: "AC Milan vs. Inter Milan"
        selection:
            type: string
            example: "1"
        market:
            type: string
            example: "1x2"
        eventPart:
            type: string
            example: "Whole Match"
        betType:
            type: string
            example: "Single"
        isPrematch:
            type: string
            example: "Pre-Match"
        currency:
            type: string
            example: "USD"
        stake:
            type: number
            example: 123.34
        bonus: 
            type: number
            example: 0.00
        oddsType: 
            type: string
            example: "Decimal, US"
        odds:
            type: number
            example: 1.34
        oddsAdjusted:
            type: boolean
            example: true   
        potentialWin:
            type: number
            example: 100.23
        risk:
            type: number
            example: 100.23
        payout:
            type: number
            example: 100.23
        balance: 
            type: number
            example: 100000.45
        status: 
            type: string
            example: "Won"
        startTime:
            type: string
            example: "1671511820"
        settleTime:
            type: string
            example: "1671511820"
        userLocation:
            type: string
            example: "Chicago, IL" 
  requestBodies:
    OddsAdjustment:
      description: Odds Adjustment Body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AdjustmentRequestSimple'
  securitySchemes:
    adr_auth:
      type: apiKey
      name: api_session_key
      in: header
  responses:
    InvalidApiRequest:
      description: Invalid Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Missing Authorization Token"
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Expired token. Use the refresh token to get a new one"
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "You are no longer an active user here"    